[package]
name = "dripper"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.1.2", directory = "noir-projects/aztec-nr/aztec" }
token = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "v1.1.0", directory = "src/token_contract" }
