name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    environment:
      name: ${{ github.ref_name == 'main' && 'Production' || 'Preview' }}

    steps:
      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "Error: VERCEL_TOKEN is not set. Please add this secret to your repository or environment."
            exit 1
          fi

          if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "Error: VERCEL_ORG_ID is not set. Please add this secret to your repository or environment."
            exit 1
          fi

          if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "Error: VERCEL_PROJECT_ID is not set. Please add this secret to your repository or environment."
            exit 1
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*\
          cache: npm

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  
     
      - name: Detect Aztec version
        id: aztec-version
        run: |
          AZTEC_VERSION=$(node -p "require('./package.json').config.aztecVersion")
          echo "AZTEC_VERSION=$AZTEC_VERSION" >> "$GITHUB_OUTPUT"
          echo "Aztec version is $AZTEC_VERSION"

      - name: Install Aztec CLI
        run: |
          curl -s https://install.aztec.network > tmp.sh
          bash tmp.sh <<< yes "yes"

      - name: Update path
        run: echo "/home/runner/.aztec/bin" >> $GITHUB_PATH

      - name: Set Aztec version
        run: |
          VERSION=${{ steps.aztec-version.outputs.AZTEC_VERSION }} aztec-up

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        id: vercel-deployment
        uses: amondnet/vercel-action@v25.2.0
        with:
          github-token: ${{ github.event_name == 'pull_request' && secrets.GITHUB_TOKEN || '' }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID}}
          vercel-args: ${{ github.ref_name == 'main' && '--prod' || '' }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./